version: '3.7'

services:
  grafana:
    build: './grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        - aliases:
            - grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    networks:
      monitoring:
        - aliases:
            - prometheus

  postgres:
    build: './dataBase'
    ports:
      - '8999:5432'
    volumes:
      - ./dataBase/data:/var/lib/postgresql/data

  backend:
    build: './'
    ports:
      - "8888:5000"


networks:
  monitoring: