CREATE TABLE IF NOT EXISTS FILTER
(
    ID BIGSERIAL PRIMARY KEY,
    ALIAS VARCHAR(255) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULl,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS KEY_SKILLS
(
    ID BIGSERIAL PRIMARY KEY,
    ALIAS VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFESSION
(
    ID BIGSERIAL PRIMARY KEY,
    FRIENDLY_NAME VARCHAR(1000) NOT NULL,
    ALIAS VARCHAR(100) UNIQUE NOT NULL,
    SHORT_DESCRIPTION VARCHAR(500) NOT NULL,
    LONG_DESCRIPTION VARCHAR(5000),
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS SPECIALIST
(
    ID BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(1000),
    DEPARTMENT VARCHAR(1000),
    PORTFOLIO_LINK VARCHAR(1000),
    ABOUT_ME VARCHAR(5000),
    WORKING_CONDITIONS VARCHAR(1000),
    EDUCATION_GRADE VARCHAR(1000),
    CONTACT_LINKS VARCHAR(1000),
    IS_COMPLETELY_FILLED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_VISIBLE BOOLEAN NOT NULL DEFAULT FALSE,
    TELEGRAM_USER_ID BIGINT,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL,

    FOREIGN KEY (TELEGRAM_USER_ID) REFERENCES TELEGRAM_USER(ID)
);

CREATE TABLE IF NOT EXISTS SPECIALISTS_TO_PROFESSIONS
(
    SPECIALIST_ID BIGINT NOT NULL REFERENCES SPECIALIST(ID),
    PROFESSION_ID BIGINT NOT NULL REFERENCES PROFESSION(ID)
);

CREATE TABLE IF NOT EXISTS TELEGRAM_CHAT
(
    ID BIGSERIAL PRIMARY KEY,
    TELEGRAM_CHAT_ID BIGINT NOT NULL,
    CHAT_TYPE VARCHAR(1000) NOT NULL,
    TITLE VARCHAR(1000),
    DESCRIPTION VARCHAR(5000),
    INVITE_LINK VARCHAR(1000),
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TELEGRAM_USER
(
    ID BIGSERIAL PRIMARY KEY,
    TELEGRAM_USER_ID BIGINT UNIQUE NOT NULL,
    PERSONAL_TELEGRAM_CHAT_ID BIGINT UNIQUE NOT NULL,
    CURRENT_BOT_STATE VARCHAR(500) NOT NULL,
    FIRST_NAME VARCHAR(1000),
    LAST_NAME VARCHAR(1000),
    USER_NAME VARCHAR(1000),
    IS_BOT BOOLEAN NOT NULL,
    LANGUAGE_CODE VARCHAR(255),
    SPECIALIST_ID BIGINT,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL,

    FOREIGN KEY (SPECIALIST_ID) REFERENCES SPECIALIST(ID)
);

CREATE TABLE IF NOT EXISTS TELEGRAM_USER_TO_SPECIALISTS_REQUESTS
(
    TELEGRAM_USER_ID BIGINT NOT NULL REFERENCES TELEGRAM_USER(ID),
    SPECIALIST_ID BIGINT NOT NULL REFERENCES SPECIALIST(ID)
);