global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['backend:5000']