FROM postgres:14-alpine
MAINTAINER Matvey_Popov
ENV POSTGRES_PASSWORD=WhatIsMyNameDarling?
ENV POSTGRES_USER=user_main_admin
ENV POSTGRES_DB=spec_market
RUN apk add --no-cache tzdata
EXPOSE 8999
ENV TZ=Europe/London